#!/bin/sh

VERSION="2.1"
HOME=../unify
NAME=nextim_$VERSION

rm -rf webim $NAME

echo "nextim dir is " $HOME
cp -R $HOME webim 

cd webim 
make clean && make
rm static/webim.all.js
rm static/webim.css
rm -rf static_src* Makefile
cd ..

mkdir $NAME
mv webim $NAME/
zip -r $NAME.zip $NAME
rm -rf webim $NAME
