#!/bin/sh

RELEASE=$PWD
VERSION=2.2
SITE_PATH=/var/www/update.nextim.cn 
echo "${VERSION}" > ../update/version
NAME=nextim_$VERSION
rm -rf $NAME*
WEBIM=$RELEASE/$NAME/webim
cd ../..
BASE=$PWD

mkdir $NAME
cp -R $PWD/webim $NAME/
mv $NAME $RELEASE
cd $WEBIM

make clean && make
rm -rf release
rm -rf static_*
find ./ -name ".git*"  | xargs rm -rf
find ./ -name ".*.swp"  | xargs rm -rf
find ./ -type f -name "*.php" -exec sed -i '1s/^\xef\xbb\xbf//' {}  \;

cd $RELEASE/$NAME
cp ../release.py  ./
python release.py webim $VERSION
#python release.py webim $VERSION
rm release.py && cd ..
echo "Compressing archive ..."
zip -r $NAME.zip $NAME

rm -rf  $SITE_PATH/webim
echo "Copy to  Auto-Update-Runtime"
cp -R  $NAME/webim  $SITE_PATH/

